### ISSUE TITLE
Enregistrer ID utilisateur

### ISSUE THREAD

**Issue by Antoine-Bergerault** [Antoine-Bergerault/Projectoi-managerv2#12]
Est-ce que ce ne serai pas une bonne idée d'enregistrer l'id de l'utilisateur lorsqu'il se connecte ? D'après le UserModel il me semble que pour le moment uniquement l'email est enregistré.

**Comment by nextrie** [comment]
On peut enregistrer tout ce qui te semble nécessaire, il n'y a effectivement que le mail qui est stocké pour le moment.

A quoi correspond l'id de l'utilisateur ici exactement et en aurait-on l'usage ?

**Comment by Antoine-Bergerault** [comment]
L'id reste et restera unique, il peut être utile à l'avenir pour certaines requêtes (même si j'en n'ai pas en tête). On peut penser que l'email puisse être changé par la suite.

**Comment by nextrie** [comment]
A quel moment le serveur transmet son id au client ?

**Comment by Antoine-Bergerault** [comment]
Pour l'instant l'api ne le renvoie pas mais garde tout en session.
Je peux renvoyer quelques infos lors de la connexion en valeur d'une clé "data" dans le json de réponse si c'est bon pour toi

**Comment by nextrie** [comment]
yes ça me vas, après si l'id n'est utilisé pour aucune requête ça vaut vraiment le coup de le stocker ?

**Comment by Antoine-Bergerault** [comment]
Yes c'est vrai que dans l'immédiat c'est pas vraiment nécessaire mais par la suite ça pourrait être utile

**Comment by Antoine-Bergerault** [comment]
La documentation de l'api est mise à jour. Tu as maintenant ce type de retour
`{
    "status": 200,
    "success": true,
    "data": {
        "id": 5,
        "email": "test@test.fr",
        "name": "test"
    }
}`

**Comment by nextrie** [comment]
ah l'id est pas généré de façon random du coup, j'avais mal compris.
Mais quelqu'un qui est connecté avec test@test.fr pourra pas acceder a `profile/edit` d'un autre mail si ? (en terme sécurité c'est déjà check tout ça ?)

**Comment by Antoine-Bergerault** [comment]
Oui je gère ça dans l'api. En fait je connecte l'api au compte utilisateur et via l'id je peux restreindre toutes les requêtes à l'utilisateur courant uniquement. Par exemple pas besoin de renseigner l'id pour récupérer les factures car c'est déjà géré côté api. En vrai c'est clair qu'en fait on n'a pas besoin de l'id dès maintenant. Stocker l'email et le nom peut permettre d'afficher des infos sur le manager sans faire de nouvelles requêtes à l'api, mais ce que je voulais surtout dire c'est que si jamais on a besoin d'identifier l'utilisateur ce sera via un id.

On peut peut-être fermer cette issue en attendant de se retrouver dans un cas concret

**Comment by nextrie** [comment]
ça marche, on en re-discutera a la réunion de demain
