### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by Ewan-skyrow** [Antoine-Bergerault/Projectoi-managerv2#2]
Le texte ne s'affiche plus malgré le `display: inline-block;` 

Les icônes ont une class avec leur couleur etc, mais elles ne prennent pas la position que je leur ai attribué. Donc elles ont une position aléatoire.

**Comment by nextrie** [comment]
Quel texte ne s'affiche plus ? Il est bien chargé dans le html quand tu inspecte l'element ?

**Comment by Antoine-Bergerault** [comment]
Les icônes ne peuvent pas avoir de position aléatoire. Si elles sont mal positionnées c'est parce qu'il y a une erreur dans le code

**Comment by Ewan-skyrow** [comment]
Alex, non il ne s'affiche pas et Antoine, ce que je comprends pas c'est qu'elles ne prennent pas la position indiquée dans leurs class, car dans mon local ça fonctionnait et plus maintenant

**Comment by nextrie** [comment]
@Ewan-skyrow @Antoine-Bergerault Bug toujours la ou on peut fermer l'issue ?

**Comment by Antoine-Bergerault** [comment]
On a toujours des pbs sur le style de la sidebar qui ne correspond pas à la maquette

**Comment by nextrie** [comment]
Sidebar merge, on peut fermer l'issue
