### ISSUE TITLE
Ajout de style pour structurer les pages

### ISSUE THREAD

**Issue by Antoine-Bergerault** [Antoine-Bergerault/Projectoi-managerv2#31]
Ajout de classes css pour permettre de structurer rapidement les pages.

Si vous avez des idées d'éléments n'hésitez pas à commenter.

Dispo sur la page /example de la branche `style-update`

![image](https://user-images.githubusercontent.com/24703287/83070541-ee689e80-a06b-11ea-87f1-4e29b6e46a6b.png)

**Comment by Antoine-Bergerault** [comment]
Besoin d'aide pour supprimer le liseret blanc à gauche sur les blocs de couleurs (classes `border-primary` et `border-secondary`)

**Comment by nextrie** [comment]
le liseret blanc ? t'as un screen ?

**Comment by Antoine-Bergerault** [comment]
@nextrie Merci de m'avoir poke. Ma petite théorie est que mes yeux étaient un peu fatigués hier soir, du coup je ne vois plus de liseret blanc
En tout cas maintenant ça semble ok

**Comment by nextrie** [comment]
Okok top, je ferme l'issue
