### ISSUE TITLE
Activer les CORS sur le serveur

### ISSUE THREAD

**Issue by nextrie** [Antoine-Bergerault/Projectoi-managerv2#7]
Hello, je ne peut pas faire de requetes a l'api en passant par react tant que les CORS ne sont pas activée côté serveur :

https://prnt.sc/sbx3az

**Comment by Antoine-Bergerault** [comment]
@nextrie Je viens de régler ça. Tu peux fermer cette issue si ça marche de ton côté sinon dis le moi

**Comment by nextrie** [comment]
ça marche niquel, merci !
